# Generated by Django 5.2.3 on 2025-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price', models.PositiveIntegerField(help_text='price per night')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=140)),
                ('pet_allowed', models.BooleanField(default=False, help_text='Does this house allow pets', verbose_name='Pets Allowed?')),
            ],
        ),
    ]
